### ISSUE TITLE
What’s the license?

### ISSUE THREAD

**Issue by JanX2** [tinyfool/webrtc-vad#1]
Hi!

What’s the license for your code in this library? Not the WebRTC part, of course. Its license is here:
https://webrtc.org/license/software/

Can you please extend the license above to your code or add another license?

Thank you!
Jan

**Comment by tinyfool** [comment]
Thank you for your advice,  I just added the WebRTC license.

**Comment by JanX2** [comment]
Thank you @tinyfool!

**Comment by tinyfool** [comment]
；）
